# This file controls the AWS CodeBuild

version: 0.2
phases:
  install:
     runtime-versions:
       java: openjdk8
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn compile
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mvn package
    - mkdir artifact
    - unzip target/aws-elastic-beanstalk-example-2-0.0.1-SNAPSHOT.war -d artifact/
artifacts:
  files:
    - artifact/**/*
cache:
  paths:
    - '/root/.m2/**/*'